const languages = {
  english: {
    APP_HEADER_TITLE: "Map Creator",
    HANDLE_THEME_LABEL: "Dark Mode",
    DEFAULT_MAP_TITLE: "Untitled",
    GRID_SELECTOR_COLUMNS_LABEL: "Columns",
    GRID_SELECTOR_ROWS_LABEL: "Rows",
    LAYER_DEFAULT_NAME: "Layer",
    RENAME_LAYERS_SUBMIT_BUTTON: "Rename",
    EXPORT_MAP_BUTTON: "Export",
    IMPORT_MAP_BUTTON: "Import",
    NEW_MAP_BUTTON: "New Map",
    ExportPNG_MAP_BUTTON: "Download",
  },
  español: {
    APP_HEADER_TITLE: "Creador de Mapa",
    HANDLE_THEME_LABEL: "Modo Oscuro",
    DEFAULT_MAP_TITLE: "Sin Título",
    GRID_SELECTOR_COLUMNS_LABEL: "Columnas",
    GRID_SELECTOR_ROWS_LABEL: "Filas",
    LAYER_DEFAULT_NAME: "Capa",
    RENAME_LAYERS_SUBMIT_BUTTON: "Renombrar",
    EXPORT_MAP_BUTTON: "Exportar",
    IMPORT_MAP_BUTTON: "Importar",
    NEW_MAP_BUTTON: "Nuevo Mapa",
    ExportPNG_MAP_BUTTON: "Descargar",
  },
  Italiano: {
    APP_HEADER_TITLE: "Creatore di Mappe",
    HANDLE_THEME_LABEL: "Modalità scura",
    DEFAULT_MAP_TITLE: "Senza titolo",
    GRID_SELECTOR_COLUMNS_LABEL: "Colonne",
    GRID_SELECTOR_ROWS_LABEL: "Righe",
    LAYER_DEFAULT_NAME: "Strato",
    RENAME_LAYERS_SUBMIT_BUTTON: "Rinominare",
    EXPORT_MAP_BUTTON: "Exportare",
    IMPORT_MAP_BUTTON: "Importare",
    NEW_MAP_BUTTON: "Nuova Mappa",
    ExportPNG_MAP_BUTTON: "Scaricamento",
  },
  Deutsch: {
    APP_HEADER_TITLE: "Kartenersteller",
    HANDLE_THEME_LABEL: "Dunkler Modus",
    DEFAULT_MAP_TITLE: "Ohne Titel",
    GRID_SELECTOR_COLUMNS_LABEL: "Säulen",
    GRID_SELECTOR_ROWS_LABEL: "Reihen",
    LAYER_DEFAULT_NAME: "Schicht",
    RENAME_LAYERS_SUBMIT_BUTTON: "Umbenennen",
    EXPORT_MAP_BUTTON: "Export",
    IMPORT_MAP_BUTTON: "Importieren",
    NEW_MAP_BUTTON: "Neue Karte",
    ExportPNG_MAP_BUTTON: "Herunterladen",
  },
  Esperanto: {
    APP_HEADER_TITLE: "Map Kreinto",
    HANDLE_THEME_LABEL: "Malhela Reĝimo",
    DEFAULT_MAP_TITLE: "Sentitola",
    GRID_SELECTOR_COLUMNS_LABEL: "Kolumnoj",
    GRID_SELECTOR_ROWS_LABEL: "Vicoj",
    LAYER_DEFAULT_NAME: "Tavolo",
    RENAME_LAYERS_SUBMIT_BUTTON: "Alinomi",
    EXPORT_MAP_BUTTON: "Eksporti",
    IMPORT_MAP_BUTTON: "Importi",
    NEW_MAP_BUTTON: "Nova Mapo",
    ExportPNG_MAP_BUTTON: "Elŝutu",
  },
};

export default languages;
